name: reporthax

on: 
  workflow_dispatch:
    inputs:
      actionid:
        required: true
      tunnel:
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Starting Report
      run: ./main.py ${{ github.event.inputs.actionid }} ${{github.event.inputs.tunnel}}
    - name: Keep Alive
      run: ./timeout.ps1
