name: lol

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14-large

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./install.sh
    - name: Keep Alive
      run: ./timeout.sh
